/************************************
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
**************************************/

#include<iostream>

int main()
{
    int answer = 2; // already 2 because b = 2 & it's even but while loop is not adding it  
    int num = 0;// curent number on seqence
    int a = 1;// a&b are first to number in sequence
    int b = 2; 

    while(num < 4000000)// should be less than 4 million
    {
        num = a + b; // updation of current number 
        a = b; // updation of a
        b = num; // updation of b

        if(num % 2 == 0) // if even add to answer
        {
            answer = answer + num;
        }
    }
       
    std:: cout << answer;
}